### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by seahyinghang8** [scanner-research/scannertools#9]
After installing tensorflow, pandas and facenet to the code, the program still crashes. It prints out an extremely long error message, probably one for each core.

Print out right before the error:
Colocations handled automatically by placer.

Error:
Traceback (most recent call last):
  File "/home/seahyh/.local/lib/python3.5/site-packages/scannerpy/kernel.py", line 105, in python_kernel_fn
    result = kernel.execute(data)
  File "/home/seahyh/.local/lib/python3.5/site-packages/scannerpy/op.py", line 556, in execute
    return parse_ret(exec_fn(self, **args))
  File "/home/seahyh/scannertools/scannertools/scannertools/face_detection.py", line 26, in execute
    self.sess, os.path.dirname(align.__file__))
  File "/home/seahyh/facenet/src/align/detect_face.py", line 283, in create_mtcnn
    pnet.load(os.path.join(model_path, 'det1.npy'), sess)
  File "/home/seahyh/facenet/src/align/detect_face.py", line 85, in load
    data_dict = np.load(data_path, encoding='latin1').item() #pylint: disable=no-member
  File "/home/seahyh/.local/lib/python3.5/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/seahyh/.local/lib/python3.5/site-packages/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by willcrichton** [comment]
What's the version of tensorflow and numpy?

**Comment by seahyinghang8** [comment]
tensorflow==1.13.1
numpy==1.16.0

**Comment by willcrichton** [comment]
Looks like an issue where facenet needs to get updated. For now, let's just enforce numpy==1.15.4.
